etcd_endpoints:
  - "http://127.0.0.1:2377"
  - "http://127.0.0.1:2378"
  - "http://127.0.0.1:2379"
log_dir: "/var/log/gin-mesh"  #"/Users/danlongpan/goproject/gin-mesh"  "/var/log"
log_name:
  stat_log_file: "go_info"
  error_log_file: "go_error"
  panic_log_file: "go_panic"
  stderr_panic_log_file: "go_Stderr_panic"
grpc_port: "7070"